### ISSUE TITLE
Warning: React does not recognize the `unmountOnExit` prop on a DOM element. 

### ISSUE THREAD

**Issue by mpyw** [gabiseabra/styled-transition-group#6]
```jsx
import transition from "styled-transition-group"

export default transition.div.attrs({
  unmountOnExit: true,
  timeout: 1000
}) `
  padding: 20px;
  background-color: #ccc;
  width: 200px;
  margin: 10px auto;
  text-align: center;
  border-radius: 4px;

  &:enter {
    opacity: 0.01;
  }
  &:enter-active {
    opacity: 1;
    transition: opacity 1000ms ease-in;
  }
  &:exit {
    opacity: 1;
  }
  &:exit-active {
    opacity: 0.01;
    transition: opacity 800ms ease-in;
  }
`
```

it causes

![2018-02-04 11 44 37](https://user-images.githubusercontent.com/1351893/35773829-df894234-09a0-11e8-9026-b59b9f9cee89.png)

**Comment by marshall-cho** [comment]
I assume this is the same case as when trying to pass `exit: false` ?

    import transition from "styled-transition-group"

    export default transition.div.attrs({
      exit: false,
    }) `
      &:enter {
        opacity: 0.01;
      }
    `
That returns this error:

![screenshot 2018-02-08 12 37 35](https://user-images.githubusercontent.com/18243389/35971090-f182c648-0ccc-11e8-9e6d-1250d7ab6e78.png)

**Comment by axhamre** [comment]
Any updates around this on the horizon? 😊

I really, really love how `styled-transition-group` works. I wish I could help out with a PR, but my domain knowledge is unfortunately still way too limited to be of any help :/

**Comment by gabiseabra** [comment]
This took a while. I had some trouble with my first approach and needed some time to clear my head but it should be working now.
Thank you for the support.
